export interface SaepError {
  code: number;
  name: string;
  msg: string;
  program: string;
}

type ErrorEntry = { name: string; msg: string };

export const AgentRegistryErrors = {
  Unauthorized: 6000,
  Paused: 6001,
  InvalidCapability: 6002,
  StakeBelowMinimum: 6003,
  AgentExists: 6004,
  AgentNotFound: 6005,
  InvalidStatusTransition: 6006,
  SlashPending: 6007,
  SlashBoundExceeded: 6008,
  TimelockNotElapsed: 6009,
  WithdrawalPending: 6010,
  NoPendingSlash: 6011,
  NoPendingWithdrawal: 6012,
  ArithmeticOverflow: 6013,
  InvalidManifest: 6014,
  CallerNotTaskMarket: 6015,
  NoPendingAuthority: 6016,
  SlashCapTooHigh: 6017,
  ReputationOutOfRange: 6018,
  UnauthorizedReputationUpdate: 6019,
  InvalidCapabilityBit: 6020,
  CapabilityNotDeclared: 6021,
  ReputationReplay: 6022,
  PersonhoodRequired: 6023,
  PersonhoodExpired: 6024,
  PersonhoodRevoked: 6025,
  GatekeeperNotAllowed: 6026,
  AttestationOperatorMismatch: 6027,
  GatewayTokenInvalid: 6028,
  GatewayTokenNotActive: 6029,
  GatewayTokenOwnerMismatch: 6030,
  GatekeeperListFull: 6031,
  AttestationStillValid: 6032,
  ReentrancyDetected: 6033,
  UnauthorizedCaller: 6034,
  CallerGuardNotActive: 6035,
  CpiDepthExceeded: 6036,
  GuardAlreadyActive: 6037,
  GuardNotInitialized: 6038,
  AdminResetNotTimelocked: 6039,
  CivicGatewayProgramNotSet: 6040,
  CivicGatewayProgramMismatch: 6041,
  InvalidCivicGateway: 6042,
} as const;

export const CapabilityRegistryErrors = {
  Unauthorized: 6000,
  AlreadyInitialized: 6001,
  BitIndexOutOfRange: 6002,
  TagAlreadyExists: 6003,
  TagNotFound: 6004,
  TagRetired: 6005,
  InvalidSlug: 6006,
  InvalidManifestUri: 6007,
  InvalidCapability: 6008,
  Paused: 6009,
  NoPendingAuthority: 6010,
  TagCountOverflow: 6011,
  InvalidPersonhoodTier: 6012,
} as const;

export const DisputeArbitrationErrors = {
  Unauthorized: 6000,
  ReentrancyDetected: 6001,
  UnauthorizedCaller: 6002,
  CallerGuardNotActive: 6003,
  CpiDepthExceeded: 6004,
  GuardAlreadyActive: 6005,
  GuardNotInitialized: 6006,
  AdminResetNotTimelocked: 6007,
  Paused: 6008,
  PoolMissing: 6009,
  PoolTooSmall: 6010,
  VrfStale: 6011,
  VrfNotFulfilled: 6012,
  WrongStatus: 6013,
  CommitWindowClosed: 6014,
  RevealWindowClosed: 6015,
  RevealWindowOpen: 6016,
  CommitHashMismatch: 6017,
  DuplicateVote: 6018,
  ArbitratorNotSelected: 6019,
  AppealWindowClosed: 6020,
  AppealCollateralInsufficient: 6021,
  TooManyAppeals: 6022,
  SlashAlreadyPending: 6023,
  SlashTimelockNotElapsed: 6024,
  NoMajority: 6025,
  VerdictEncodingInvalid: 6026,
  StakeInsufficient: 6027,
  StakeLockTooShort: 6028,
  ArithmeticOverflow: 6029,
  CallerNotTaskMarket: 6030,
  ArbitratorNotActive: 6031,
  PoolFull: 6032,
  AlreadyRegistered: 6033,
  AppealWindowOpen: 6034,
  ExecutionWindowOpen: 6035,
  NotWithdrawing: 6036,
  WithdrawNotReady: 6037,
  BadFaithThresholdNotMet: 6038,
  InvalidBps: 6039,
} as const;

export const FeeCollectorErrors = {
  Unauthorized: 6000,
  HookNotAllowed: 6001,
  HookAllowlistFull: 6002,
  AgentHookAllowlistFull: 6003,
  InvalidProgramId: 6004,
  MintExtensionRejected: 6005,
  MintParseFailed: 6006,
  NoPendingAuthority: 6007,
  ReentrancyDetected: 6008,
  UnauthorizedCaller: 6009,
  CallerGuardNotActive: 6010,
  CpiDepthExceeded: 6011,
  GuardAlreadyActive: 6012,
  GuardNotInitialized: 6013,
  AdminResetNotTimelocked: 6014,
  Paused: 6015,
  InvalidBpsSum: 6016,
  BucketCapExceeded: 6017,
  EpochNotOpen: 6018,
  EpochNotElapsed: 6019,
  IntakeAccountingDrift: 6020,
  DistributionAlreadyCommitted: 6021,
  DistributionWindowElapsed: 6022,
  MerkleProofInvalid: 6023,
  MerkleProofTooDeep: 6024,
  ClaimOverflow: 6025,
  ClaimWindowElapsed: 6026,
  BurnBelowThreshold: 6027,
  BurnAlreadyExecuted: 6028,
  SweepGraceNotElapsed: 6029,
  AlreadySwept: 6030,
  InvalidEpochStatus: 6031,
  ArithmeticOverflow: 6032,
  CallerNotRegisteredSlasher: 6033,
  InvalidEpochDuration: 6034,
  InvalidClaimWindow: 6035,
} as const;

export const GovernanceProgramErrors = {
  Unauthorized: 6000,
  Paused: 6001,
  InvalidProposalStatus: 6002,
  VotingNotEnded: 6003,
  VotingEnded: 6004,
  TimelockNotElapsed: 6005,
  ExecutionWindowExpired: 6006,
  QuorumNotMet: 6007,
  MerkleProofInvalid: 6008,
  MerkleProofTooDeep: 6009,
  RegistryFull: 6010,
  DuplicateProgram: 6011,
  ProgramNotRegistered: 6012,
  ArithmeticOverflow: 6013,
  PayloadTooLarge: 6014,
  CannotCancelAfterVoteStart: 6015,
  EmptyMetadataUri: 6016,
} as const;

export const NxsStakingErrors = {
  Unauthorized: 6000,
  ReentrancyDetected: 6001,
  UnauthorizedCaller: 6002,
  CallerGuardNotActive: 6003,
  CpiDepthExceeded: 6004,
  GuardAlreadyActive: 6005,
  GuardNotInitialized: 6006,
  AdminResetNotTimelocked: 6007,
  Paused: 6008,
  InvalidLockup: 6009,
  ZeroAmount: 6010,
  LockupNotEnded: 6011,
  CooldownNotEnded: 6012,
  NotActive: 6013,
  NotInCooldown: 6014,
  ArithmeticOverflow: 6015,
  EpochNotEnded: 6016,
} as const;

export const ProofVerifierErrors = {
  Unauthorized: 6000,
  Paused: 6001,
  VkAlreadyExists: 6002,
  VkNotFound: 6003,
  VkMismatch: 6004,
  PublicInputCountMismatch: 6005,
  PublicInputOutOfField: 6006,
  ProofMalformed: 6007,
  ProofInvalid: 6008,
  TimelockNotElapsed: 6009,
  NoPendingActivation: 6010,
  ActivationPending: 6011,
  NotProductionVk: 6012,
  IcLengthMismatch: 6013,
  TooManyPublicInputs: 6014,
  NoPendingAuthority: 6015,
  NotImplemented: 6016,
  InvalidBatchSize: 6017,
  BatchFull: 6018,
  BatchEmpty: 6019,
  BatchVkMismatch: 6020,
  ReentrancyDetected: 6021,
  UnauthorizedCaller: 6022,
  CallerGuardNotActive: 6023,
  CpiDepthExceeded: 6024,
  GuardAlreadyActive: 6025,
  GuardNotInitialized: 6026,
  AdminResetNotTimelocked: 6027,
  ReputationBindingNotReady: 6028,
} as const;

export const TaskMarketErrors = {
  Unauthorized: 6000,
  Paused: 6001,
  MintNotAllowed: 6002,
  InvalidAmount: 6003,
  InvalidDeadline: 6004,
  DeadlineTooFar: 6005,
  AgentNotActive: 6006,
  WrongStatus: 6007,
  DeadlinePassed: 6008,
  DisputeWindowClosed: 6009,
  DisputeWindowOpen: 6010,
  NotExpired: 6011,
  EscrowMismatch: 6012,
  ArithmeticOverflow: 6013,
  ProofInvalid: 6014,
  CallerNotOperator: 6015,
  TaskNotFound: 6016,
  FeeBoundExceeded: 6017,
  TooManyMilestones: 6018,
  NoPendingAuthority: 6019,
  GraceNotElapsed: 6020,
  ZeroResultHash: 6021,
  AgentMismatch: 6022,
  OutcomeCpiFailed: 6023,
  InsufficientStake: 6024,
  PhaseClosed: 6025,
  RevealMismatch: 6026,
  BondOutOfRange: 6027,
  TooManyBidders: 6028,
  BidBookNotSettled: 6029,
  NotWinner: 6030,
  NoReveals: 6031,
  AlreadyRefunded: 6032,
  WindowInvalid: 6033,
  BidBookAlreadyOpen: 6034,
  CommitsPresent: 6035,
  PayloadTooLarge: 6036,
  InvalidCapabilityBit: 6037,
  UnknownCapability: 6038,
  PersonhoodRequired: 6039,
  PersonhoodExpired: 6040,
  PersonhoodRevoked: 6041,
  AttestationOperatorMismatch: 6042,
  HookNotAllowed: 6043,
  MintExtensionRejected: 6044,
  HookAllowlistMismatch: 6045,
  MintAlreadyAccepted: 6046,
  ReentrancyDetected: 6047,
  UnauthorizedCaller: 6048,
  CallerGuardNotActive: 6049,
  CpiDepthExceeded: 6050,
  GuardAlreadyActive: 6051,
  GuardNotInitialized: 6052,
  AdminResetNotTimelocked: 6053,
  IncompleteBidEnumeration: 6054,
  DuplicateBidEnumeration: 6055,
  CapabilityNotInAgentMask: 6056,
  InvalidBidInEnumeration: 6057,
  BondNotClaimed: 6058,
  EscrowNotEmpty: 6059,
} as const;

export const TemplateRegistryErrors = {
  Paused: 6000,
  Unauthorized: 6001,
  RoyaltyExceedsCap: 6002,
  InvalidStatus: 6003,
  LineageDepthExceeded: 6004,
  CapabilityMaskMismatch: 6005,
  RentalDisabled: 6006,
  RentalDurationOutOfBounds: 6007,
  RentalNotEnded: 6008,
  RentalAlreadyClosed: 6009,
  ArithmeticOverflow: 6010,
  NothingToClaim: 6011,
  InvalidCpiCaller: 6012,
  FeeSplitExceeds100: 6013,
} as const;

export const TreasuryStandardErrors = {
  Unauthorized: 6000,
  Paused: 6001,
  MintNotAllowed: 6002,
  LimitExceeded: 6003,
  InsufficientVault: 6004,
  StreamAlreadyActive: 6005,
  StreamNotActive: 6006,
  StreamAlreadyClosed: 6007,
  InvalidDuration: 6008,
  InvalidRate: 6009,
  OracleStale: 6010,
  OracleConfidenceTooWide: 6011,
  SwapSlippage: 6012,
  ArithmeticOverflow: 6013,
  CallerNotTaskMarket: 6014,
  AgentNotActive: 6015,
  InvalidLimits: 6016,
  AllowedMintsFull: 6017,
  MintNotFound: 6018,
  NoPendingAuthority: 6019,
  ZeroAmount: 6020,
  PayTaskDisabled: 6021,
  InvalidJupiterProgram: 6022,
  SwapRouteRequired: 6023,
  RouteDataTooLong: 6024,
  SwapAmountExceeded: 6025,
  OracleRequired: 6026,
  OracleNonPositivePrice: 6027,
  AgentMismatch: 6028,
  OperatorMismatch: 6029,
  TargetNotAllowed: 6030,
  TooManyCallTargets: 6031,
  InvalidCallTarget: 6032,
  HookNotAllowed: 6033,
  HookAllowlistAlreadySet: 6034,
  HookAllowlistMismatch: 6035,
  ReentrancyDetected: 6036,
  UnauthorizedCaller: 6037,
  CallerGuardNotActive: 6038,
  CpiDepthExceeded: 6039,
  GuardAlreadyActive: 6040,
  GuardNotInitialized: 6041,
  AdminResetNotTimelocked: 6042,
} as const;

function buildMap(
  errors: Record<string, number>,
): Record<number, ErrorEntry> {
  const map: Record<number, ErrorEntry> = {};
  for (const [name, code] of Object.entries(errors)) {
    map[code] = { name, msg: '' };
  }
  return map;
}

// Attach messages from the IDL error definitions inline.
// buildMap gives us the structure; we patch messages below.
const PROGRAM_ERROR_DEFS: Record<string, { errors: Record<string, number>; msgs: Record<number, string> }> = {
  agent_registry: {
    errors: AgentRegistryErrors,
    msgs: {
      6000: 'signer is not authorized for this instruction',
      6001: 'registry is paused',
      6002: 'capability mask contains unapproved bits',
      6003: 'stake is below configured minimum',
      6004: 'agent already exists for these seeds',
      6005: 'agent not found',
      6006: 'illegal status transition',
      6007: 'a slash is already pending',
      6008: 'slash amount exceeds per-incident bound',
      6009: 'slash timelock has not elapsed',
      6010: 'a withdrawal is already pending',
      6011: 'no pending slash',
      6012: 'no pending withdrawal',
      6013: 'arithmetic overflow',
      6014: 'manifest uri invalid',
      6015: 'caller is not the TaskMarket program',
      6016: 'no pending authority to accept',
      6017: 'max_slash_bps above 10% cap',
      6018: 'reputation value out of range',
      6019: 'only the proof_verifier program may update reputation',
      6020: 'capability bit exceeds capability_mask width',
      6021: 'agent has not declared this capability bit',
      6022: 'task_id already applied to this category reputation',
      6023: 'personhood attestation required but missing',
      6024: 'personhood attestation has expired',
      6025: 'personhood attestation has been revoked',
      6026: 'gatekeeper network or SAS issuer is not on the allowlist',
      6027: 'attestation operator does not match signer or bidder',
      6028: 'gateway token layout is invalid',
      6029: 'gateway token state is not active',
      6030: 'gateway token owner does not match operator',
      6031: 'gatekeeper allowlist overflow',
      6032: 'attestation is still valid; refresh not needed',
      6033: 'reentrancy detected \u2014 guard is already active',
      6034: 'caller program is not on the allowed callers list',
      6035: "caller program's reentrancy guard is not active",
      6036: 'cpi stack height exceeds allowed bound',
      6037: 'reentrancy guard is already active',
      6038: 'reentrancy guard has not been initialized',
      6039: 'admin reset has not met the 24h timelock',
      6040: 'civic gateway program id has not been configured on RegistryGlobal',
      6041: 'civic gateway token account owner does not match civic gateway program',
      6042: 'civic gateway program cannot be set to Pubkey::default',
    },
  },
  capability_registry: {
    errors: CapabilityRegistryErrors,
    msgs: {
      6000: 'signer is not the registry authority',
      6001: 'registry already initialized',
      6002: 'bit index must be < 128',
      6003: 'tag already exists for this bit index',
      6004: 'tag not found',
      6005: 'tag is retired',
      6006: 'slug must be non-empty lowercase ascii [a-z0-9_] without leading or trailing underscore',
      6007: 'manifest uri must be non-empty',
      6008: 'mask contains unapproved or retired bits',
      6009: 'registry is paused',
      6010: 'no pending authority to accept',
      6011: 'tag count overflow',
      6012: 'personhood tier value out of range',
    },
  },
  dispute_arbitration: {
    errors: DisputeArbitrationErrors,
    msgs: {
      6000: 'signer is not authorized for this instruction',
      6001: 'reentrancy detected \u2014 guard is already active',
      6002: 'caller program is not on the allowed callers list',
      6003: "caller program's reentrancy guard is not active",
      6004: 'cpi stack height exceeds allowed bound',
      6005: 'reentrancy guard is already active',
      6006: 'reentrancy guard has not been initialized',
      6007: 'admin reset has not met the 24h timelock',
      6008: 'program is paused',
      6009: 'dispute pool has not been snapshotted',
      6010: 'dispute pool has too few eligible arbitrators',
      6011: 'VRF result is stale',
      6012: 'VRF has not been fulfilled',
      6013: 'invalid status for this operation',
      6014: 'commit window has closed',
      6015: 'reveal window has closed',
      6016: 'reveal window has not closed yet',
      6017: 'commit hash does not match revealed data',
      6018: 'arbitrator has already voted in this round',
      6019: 'arbitrator was not selected for this case',
      6020: 'appeal window has closed',
      6021: 'appeal collateral is insufficient',
      6022: 'maximum number of appeals reached',
      6023: 'a pending slash already exists for this arbitrator',
      6024: 'slash timelock has not elapsed',
      6025: 'no clean majority was reached',
      6026: 'verdict encoding is invalid',
      6027: 'stake is below minimum requirement',
      6028: 'stake lockup is too short',
      6029: 'arithmetic overflow',
      6030: 'caller is not the task market program',
      6031: 'arbitrator is not active',
      6032: 'pool is at maximum capacity',
      6033: 'arbitrator already registered',
      6034: 'appeal window has not elapsed',
      6035: 'execution window has not elapsed',
      6036: 'arbitrator is not in withdrawing status',
      6037: 'withdraw unlock time has not been reached',
      6038: 'bad faith threshold not met for slash',
      6039: 'invalid bps value',
    },
  },
  fee_collector: {
    errors: FeeCollectorErrors,
    msgs: {
      6000: 'signer is not authorized for this instruction',
      6001: 'transfer-hook program is not on the allowlist',
      6002: 'hook allowlist is at capacity',
      6003: 'per-agent hook allowlist is at capacity',
      6004: 'program id must be a non-default pubkey',
      6005: 'mint extension configuration is not acceptable',
      6006: 'failed to parse Token-2022 mint extensions',
      6007: 'no pending authority to accept',
      6008: 'reentrancy detected \u2014 guard is already active',
      6009: 'caller program is not on the allowed callers list',
      6010: "caller program's reentrancy guard is not active",
      6011: 'cpi stack height exceeds allowed bound',
      6012: 'reentrancy guard is already active',
      6013: 'reentrancy guard has not been initialized',
      6014: 'admin reset has not met the 24h timelock',
      6015: 'program is paused',
      6016: 'bps quadruple must sum to 10000',
      6017: 'bucket bps exceeds its hard cap',
      6018: 'epoch is not in Open status',
      6019: 'epoch duration has not elapsed',
      6020: 'intake vault balance does not match total_collected',
      6021: 'distribution root already committed for this epoch',
      6022: 'distribution commit window has elapsed',
      6023: 'merkle proof is invalid',
      6024: 'merkle proof exceeds max depth',
      6025: 'claim would exceed staker_amount for this epoch',
      6026: 'claim window has elapsed',
      6027: 'burn amount below minimum threshold',
      6028: 'burn already executed for this epoch',
      6029: 'sweep grace period has not elapsed',
      6030: 'epoch has already been swept',
      6031: 'invalid epoch status for this operation',
      6032: 'arithmetic overflow',
      6033: 'caller is not a registered slash source',
      6034: 'epoch duration out of allowed range',
      6035: 'claim window out of allowed range',
    },
  },
  governance_program: {
    errors: GovernanceProgramErrors,
    msgs: {
      6000: 'signer is not authorized',
      6001: 'governance is paused',
      6002: 'proposal is not in the expected status',
      6003: 'voting window has not ended',
      6004: 'voting window has ended',
      6005: 'timelock has not elapsed',
      6006: 'execution window has expired',
      6007: 'quorum was not met',
      6008: 'merkle proof is invalid',
      6009: 'merkle proof exceeds max depth',
      6010: 'program registry is at capacity',
      6011: 'duplicate program in registry',
      6012: 'target program not found in registry',
      6013: 'arithmetic overflow',
      6014: 'ix_data exceeds max payload size for target program',
      6015: 'proposal cannot be cancelled after voting starts',
      6016: 'metadata_uri is empty',
    },
  },
  nxs_staking: {
    errors: NxsStakingErrors,
    msgs: {
      6000: 'signer is not authorized for this instruction',
      6001: 'reentrancy detected \u2014 guard is already active',
      6002: 'caller program is not on the allowed callers list',
      6003: "caller program's reentrancy guard is not active",
      6004: 'cpi stack height exceeds allowed bound',
      6005: 'reentrancy guard is already active',
      6006: 'reentrancy guard has not been initialized',
      6007: 'admin reset has not met the 24h timelock',
      6008: 'staking pool is paused',
      6009: 'lockup duration out of allowed range',
      6010: 'amount must be greater than zero',
      6011: 'lockup period has not ended',
      6012: 'cooldown period has not ended',
      6013: 'stake account is not active',
      6014: 'stake account is not in cooldown',
      6015: 'arithmetic overflow',
      6016: 'epoch has not ended yet',
    },
  },
  proof_verifier: {
    errors: ProofVerifierErrors,
    msgs: {
      6000: 'signer is not the verifier authority',
      6001: 'verifier is paused',
      6002: 'verifying key already exists',
      6003: 'verifying key not found',
      6004: 'provided verifying key does not match active vk',
      6005: 'public input count does not match verifying key',
      6006: 'public input exceeds bn254 scalar field modulus',
      6007: 'proof bytes failed curve deserialization',
      6008: 'pairing check failed',
      6009: 'timelock has not elapsed',
      6010: 'no pending vk activation',
      6011: 'a vk activation is already pending',
      6012: 'non-production vk cannot be activated in mainnet mode',
      6013: 'ic length must equal num_public_inputs + 1',
      6014: 'num_public_inputs exceeds m1 cap of 16',
      6015: 'no pending authority to accept',
      6016: 'not implemented in m1',
      6017: 'batch size must be 1-10',
      6018: 'batch is full',
      6019: 'batch has no proofs',
      6020: 'batch vk does not match active vk',
      6021: 'reentrancy detected \u2014 guard is already active',
      6022: 'caller program is not on the allowed callers list',
      6023: "caller program's reentrancy guard is not active",
      6024: 'cpi stack height exceeds allowed bound',
      6025: 'reentrancy guard is already active',
      6026: 'reentrancy guard has not been initialized',
      6027: 'admin reset has not met the 24h timelock',
      6028: 'reputation args are not yet bound to the circuit\'s public outputs; rail disabled',
    },
  },
  task_market: {
    errors: TaskMarketErrors,
    msgs: {
      6000: 'signer is not authorized for this instruction',
      6001: 'market is paused',
      6002: 'payment mint is not allowed',
      6003: 'payment amount must be positive',
      6004: 'deadline must be in the future',
      6005: 'deadline exceeds max_deadline_secs',
      6006: 'agent is not active',
      6007: 'task is in the wrong status for this instruction',
      6008: 'deadline has passed',
      6009: 'dispute window has closed',
      6010: 'dispute window is still open',
      6011: 'task is not yet expired',
      6012: 'escrow balance mismatch',
      6013: 'arithmetic overflow',
      6014: 'proof verification failed',
      6015: 'signer is not the operator of the assigned agent',
      6016: 'task not found',
      6017: 'fee bps exceeds bound',
      6018: 'milestone_count exceeds maximum',
      6019: 'no pending authority to accept',
      6020: 'grace period has not elapsed',
      6021: 'result hash must be non-zero',
      6022: 'agent DID does not match task assignment',
      6023: 'agent registry CPI failed',
      6024: 'agent stake below required minimum',
      6025: 'bid phase closed for this action',
      6026: 'revealed bid does not match commit hash',
      6027: 'bond bps out of allowed range',
      6028: 'bid book is at capacity',
      6029: 'bid book has not been settled',
      6030: 'signer is not the winning bidder',
      6031: 'no eligible reveals in bid book',
      6032: 'bond has already been claimed',
      6033: 'bid window parameters invalid',
      6034: 'task already has an open bid book',
      6035: 'bid book has active commits; cannot cancel',
      6036: 'task payload exceeds size caps',
      6037: 'capability_bit out of allowed range',
      6038: 'agent does not advertise the requested capability_bit',
      6039: 'personhood attestation required but missing',
      6040: 'personhood attestation has expired',
      6041: 'personhood attestation has been revoked',
      6042: 'attestation operator does not match bidder',
      6043: 'transfer-hook program not on fee_collector allowlist',
      6044: 'mint extension configuration is not acceptable',
      6045: 'hook_allowlist account does not match MarketGlobal hook_allowlist',
      6046: 'mint already has a MintAcceptRecord',
      6047: 'reentrancy detected \u2014 guard is already active',
      6048: 'caller program is not on the allowed callers list',
      6049: "caller program's reentrancy guard is not active",
      6050: 'cpi stack height exceeds allowed bound',
      6051: 'reentrancy guard is already active',
      6052: 'reentrancy guard has not been initialized',
      6053: 'admin reset has not met the 24h timelock',
      6054: 'close_bidding must receive every revealed bid in remaining_accounts',
      6055: 'duplicate bid detected in close_bidding enumeration',
      6056: 'agent has not declared the task\'s capability bit',
      6057: 'unrevealed or slashed bid present in close_bidding enumeration',
      6058: 'bond must be claimed before closing bid PDA',
      6059: 'bond escrow still holds tokens',
    },
  },
  template_registry: {
    errors: TemplateRegistryErrors,
    msgs: {
      6000: 'Program is paused',
      6001: 'Unauthorized',
      6002: 'Royalty bps exceeds cap',
      6003: 'Template not in valid state for this operation',
      6004: 'Lineage depth exceeds maximum',
      6005: 'Capability mask includes bits not present in parent',
      6006: 'Rental is disabled for this template',
      6007: 'Rental duration out of bounds',
      6008: 'Rental not yet ended',
      6009: 'Rental already closed',
      6010: 'Arithmetic overflow',
      6011: 'Nothing to claim',
      6012: 'Invalid CPI caller',
      6013: 'Fee split exceeds 100%',
    },
  },
  treasury_standard: {
    errors: TreasuryStandardErrors,
    msgs: {
      6000: 'signer is not authorized for this instruction',
      6001: 'treasury is paused',
      6002: 'mint is not on the allowlist',
      6003: 'spending or transfer limit exceeded',
      6004: 'vault balance insufficient',
      6005: 'a stream is already active for this treasury',
      6006: 'stream is not active',
      6007: 'stream is already closed',
      6008: 'stream duration invalid',
      6009: 'stream rate invalid',
      6010: 'oracle price is stale',
      6011: 'oracle confidence interval too wide',
      6012: 'swap exceeded slippage tolerance',
      6013: 'arithmetic overflow',
      6014: 'caller is not TaskMarket program',
      6015: 'agent is not active in AgentRegistry',
      6016: 'limits violate per_tx <= daily <= weekly invariant',
      6017: 'allowed-mints list is full',
      6018: 'mint not found in allowlist',
      6019: 'no pending authority to accept',
      6020: 'amount must be greater than zero',
      6021: 'pay_task is reserved for M2 and is inert in M1',
      6022: 'jupiter program does not match configured address',
      6023: 'swap route data required for cross-mint withdrawal',
      6024: 'route_data exceeds MAX_ROUTE_DATA_LEN',
      6025: 'swap consumed more tokens than earned',
      6026: 'oracle price feed required for cross-mint withdrawal',
      6027: 'oracle price is non-positive',
      6028: 'agent DID does not match AgentAccount',
      6029: 'operator does not match AgentAccount operator',
      6030: 'outbound CPI target is not on the allowed-call-targets list',
      6031: 'allowed-call-targets list exceeds cap',
      6032: 'call target must be a non-default pubkey',
      6033: 'transfer-hook program not on fee_collector allowlist',
      6034: 'hook_allowlist pointer has already been set',
      6035: 'hook_allowlist account does not match TreasuryGlobal.hook_allowlist',
      6036: 'reentrancy detected \u2014 guard is already active',
      6037: 'caller program is not on the allowed callers list',
      6038: "caller program's reentrancy guard is not active",
      6039: 'cpi stack height exceeds allowed bound',
      6040: 'reentrancy guard is already active',
      6041: 'reentrancy guard has not been initialized',
      6042: 'admin reset has not met the 24h timelock',
    },
  },
};

function buildFullMap(): Record<string, Record<number, ErrorEntry>> {
  const result: Record<string, Record<number, ErrorEntry>> = {};
  for (const [program, def] of Object.entries(PROGRAM_ERROR_DEFS)) {
    const map: Record<number, ErrorEntry> = {};
    for (const [name, code] of Object.entries(def.errors)) {
      map[code] = { name, msg: def.msgs[code] ?? '' };
    }
    result[program] = map;
  }
  return result;
}

export const SAEP_ERRORS: Record<string, Record<number, ErrorEntry>> = buildFullMap();

// When programName is omitted, searches all programs and returns the first match.
// Error codes overlap across programs so the result may be ambiguous without a program hint.
export function decodeSaepError(code: number, programName?: string): SaepError | null {
  if (programName) {
    const entry = SAEP_ERRORS[programName]?.[code];
    if (!entry) return null;
    return { code, ...entry, program: programName };
  }

  for (const [program, map] of Object.entries(SAEP_ERRORS)) {
    const entry = map[code];
    if (entry) return { code, ...entry, program };
  }

  return null;
}
