import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const sdkRoot = resolve(here, '..');
const repoRoot = resolve(sdkRoot, '..', '..');
const typesDir = join(repoRoot, 'target', 'types');
const idlSrcDir = join(repoRoot, 'target', 'idl');
const generatedDir = join(sdkRoot, 'src', 'generated');
const idlDir = join(sdkRoot, 'src', 'idl');
const programsDir = join(sdkRoot, 'src', 'programs');

if (!existsSync(typesDir)) {
  console.warn(
    `[sdk:gen] ${typesDir} not found — skipping regen, using committed artifacts in src/generated, src/idl, src/programs`,
  );
  process.exit(0);
}

mkdirSync(generatedDir, { recursive: true });
mkdirSync(idlDir, { recursive: true });
mkdirSync(programsDir, { recursive: true });

const pascal = (snake: string) =>
  snake.split('_').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const camel = (snake: string) => {
  const [h, ...t] = snake.split('_');
  return h + t.map((p) => p[0].toUpperCase() + p.slice(1)).join('');
};

const typeFiles = readdirSync(typesDir).filter((f) => f.endsWith('.ts'));
const programs: Array<{ snake: string; pascal: string; camel: string; address: string }> = [];

for (const file of typeFiles) {
  const snake = file.replace(/\.ts$/, '');
  const src = readFileSync(join(typesDir, file), 'utf8');
  writeFileSync(
    join(generatedDir, file),
    `// Generated by packages/sdk/scripts/gen.ts — do not edit by hand.\n\n${src}`,
  );

  const idlJsonPath = join(idlSrcDir, `${snake}.json`);
  const idl = JSON.parse(readFileSync(idlJsonPath, 'utf8')) as { address: string };
  copyFileSync(idlJsonPath, join(idlDir, `${snake}.json`));

  programs.push({
    snake,
    pascal: pascal(snake),
    camel: camel(snake),
    address: idl.address,
  });
}

programs.sort((a, b) => a.snake.localeCompare(b.snake));

writeFileSync(
  join(generatedDir, 'index.ts'),
  `// Generated by packages/sdk/scripts/gen.ts — do not edit by hand.\n\n` +
    programs.map((p) => `export type { ${p.pascal} } from './${p.snake}.js';`).join('\n') +
    '\n',
);

const programsTs =
  `// Generated by packages/sdk/scripts/gen.ts — do not edit by hand.\n\n` +
  `import { AnchorProvider, Program, Idl, type Wallet } from '@coral-xyz/anchor';\n` +
  `import { Connection, PublicKey, Transaction, VersionedTransaction } from '@solana/web3.js';\n\n` +
  programs
    .map(
      (p) =>
        `import ${p.camel}Idl from '../idl/${p.snake}.json' with { type: 'json' };`,
    )
    .join('\n') +
  '\n' +
  programs
    .map((p) => `import type { ${p.pascal} } from '../generated/${p.snake}.js';`)
    .join('\n') +
  `\nimport type { ClusterConfig, SaepProgramName } from '../cluster/index.js';\n\n` +
  `export interface BrowserWallet {\n` +
  `  publicKey: PublicKey;\n` +
  `  signTransaction<T extends Transaction | VersionedTransaction>(tx: T): Promise<T>;\n` +
  `  signAllTransactions<T extends Transaction | VersionedTransaction>(txs: T[]): Promise<T[]>;\n` +
  `}\n\n` +
  `export interface ProviderInput {\n` +
  `  connection: Connection;\n` +
  `  wallet: BrowserWallet;\n` +
  `}\n\n` +
  `export function makeProvider({ connection, wallet }: ProviderInput): AnchorProvider {\n` +
  `  return new AnchorProvider(connection, wallet as Wallet, {\n` +
  `    commitment: 'confirmed',\n` +
  `  });\n` +
  `}\n\n` +
  `function withAddress<T extends Idl>(idl: Record<string, unknown>, id: PublicKey): T {\n` +
  `  return { ...idl, address: id.toBase58() } as T;\n` +
  `}\n\n` +
  programs
    .map((p) => {
      const idName = p.camel as string;
      const programName = p.camel + 'Program';
      const clusterKey: Record<string, string> = {
        agent_registry: 'agentRegistry',
        capability_registry: 'capabilityRegistry',
        dispute_arbitration: 'disputeArbitration',
        fee_collector: 'feeCollector',
        governance_program: 'governanceProgram',
        proof_verifier: 'proofVerifier',
        task_market: 'taskMarket',
        treasury_standard: 'treasuryStandard',
      };
      const key = clusterKey[p.snake] ?? p.camel;
      return (
        `export function ${programName}(\n` +
        `  provider: AnchorProvider,\n` +
        `  config: ClusterConfig,\n` +
        `): Program<${p.pascal}> {\n` +
        `  const idl = withAddress<${p.pascal}>(${idName}Idl as Record<string, unknown>, config.programIds.${key});\n` +
        `  return new Program<${p.pascal}>(idl, provider);\n` +
        `}`
      );
    })
    .join('\n\n') +
  '\n\n' +
  `export type { ${programs.map((p) => p.pascal).join(', ')} };\n` +
  `export { PublicKey };\n` +
  `\nexport type SaepProgramFactory = (p: AnchorProvider, c: ClusterConfig) => Program<Idl>;\n`;

writeFileSync(join(programsDir, 'index.ts'), programsTs);

console.log(
  `[sdk:gen] wrote ${programs.length} program types + IDL jsons + programs/index.ts`,
);
for (const p of programs) {
  console.log(`         - ${p.snake} (${p.address})`);
}
