// Generated by packages/sdk/scripts/gen.ts — do not edit by hand.

import { AnchorProvider, Program, Idl, type Wallet } from '@coral-xyz/anchor';
import { Connection, PublicKey, Transaction, VersionedTransaction } from '@solana/web3.js';

import agentRegistryIdl from '../idl/agent_registry.json' with { type: 'json' };
import capabilityRegistryIdl from '../idl/capability_registry.json' with { type: 'json' };
import disputeArbitrationIdl from '../idl/dispute_arbitration.json' with { type: 'json' };
import feeCollectorIdl from '../idl/fee_collector.json' with { type: 'json' };
import governanceProgramIdl from '../idl/governance_program.json' with { type: 'json' };
import nxsStakingIdl from '../idl/nxs_staking.json' with { type: 'json' };
import proofVerifierIdl from '../idl/proof_verifier.json' with { type: 'json' };
import taskMarketIdl from '../idl/task_market.json' with { type: 'json' };
import templateRegistryIdl from '../idl/template_registry.json' with { type: 'json' };
import treasuryStandardIdl from '../idl/treasury_standard.json' with { type: 'json' };
import type { AgentRegistry } from '../generated/agent_registry.js';
import type { CapabilityRegistry } from '../generated/capability_registry.js';
import type { DisputeArbitration } from '../generated/dispute_arbitration.js';
import type { FeeCollector } from '../generated/fee_collector.js';
import type { GovernanceProgram } from '../generated/governance_program.js';
import type { NxsStaking } from '../generated/nxs_staking.js';
import type { ProofVerifier } from '../generated/proof_verifier.js';
import type { TaskMarket } from '../generated/task_market.js';
import type { TemplateRegistry } from '../generated/template_registry.js';
import type { TreasuryStandard } from '../generated/treasury_standard.js';
import type { ClusterConfig, SaepProgramName } from '../cluster/index.js';

export interface BrowserWallet {
  publicKey: PublicKey;
  signTransaction<T extends Transaction | VersionedTransaction>(tx: T): Promise<T>;
  signAllTransactions<T extends Transaction | VersionedTransaction>(txs: T[]): Promise<T[]>;
}

export interface ProviderInput {
  connection: Connection;
  wallet: BrowserWallet;
}

export function makeProvider({ connection, wallet }: ProviderInput): AnchorProvider {
  return new AnchorProvider(connection, wallet as Wallet, {
    commitment: 'confirmed',
  });
}

function withAddress<T extends Idl>(idl: Record<string, unknown>, id: PublicKey): T {
  return { ...idl, address: id.toBase58() } as T;
}

export function agentRegistryProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<AgentRegistry> {
  const idl = withAddress<AgentRegistry>(agentRegistryIdl as Record<string, unknown>, config.programIds.agentRegistry);
  return new Program<AgentRegistry>(idl, provider);
}

export function capabilityRegistryProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<CapabilityRegistry> {
  const idl = withAddress<CapabilityRegistry>(capabilityRegistryIdl as Record<string, unknown>, config.programIds.capabilityRegistry);
  return new Program<CapabilityRegistry>(idl, provider);
}

export function disputeArbitrationProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<DisputeArbitration> {
  const idl = withAddress<DisputeArbitration>(disputeArbitrationIdl as Record<string, unknown>, config.programIds.disputeArbitration);
  return new Program<DisputeArbitration>(idl, provider);
}

export function feeCollectorProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<FeeCollector> {
  const idl = withAddress<FeeCollector>(feeCollectorIdl as Record<string, unknown>, config.programIds.feeCollector);
  return new Program<FeeCollector>(idl, provider);
}

export function governanceProgramProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<GovernanceProgram> {
  const idl = withAddress<GovernanceProgram>(governanceProgramIdl as Record<string, unknown>, config.programIds.governanceProgram);
  return new Program<GovernanceProgram>(idl, provider);
}

export function nxsStakingProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<NxsStaking> {
  const idl = withAddress<NxsStaking>(nxsStakingIdl as Record<string, unknown>, config.programIds.nxsStaking);
  return new Program<NxsStaking>(idl, provider);
}

export function proofVerifierProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<ProofVerifier> {
  const idl = withAddress<ProofVerifier>(proofVerifierIdl as Record<string, unknown>, config.programIds.proofVerifier);
  return new Program<ProofVerifier>(idl, provider);
}

export function taskMarketProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<TaskMarket> {
  const idl = withAddress<TaskMarket>(taskMarketIdl as Record<string, unknown>, config.programIds.taskMarket);
  return new Program<TaskMarket>(idl, provider);
}

export function templateRegistryProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<TemplateRegistry> {
  const idl = withAddress<TemplateRegistry>(templateRegistryIdl as Record<string, unknown>, config.programIds.templateRegistry);
  return new Program<TemplateRegistry>(idl, provider);
}

export function treasuryStandardProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<TreasuryStandard> {
  const idl = withAddress<TreasuryStandard>(treasuryStandardIdl as Record<string, unknown>, config.programIds.treasuryStandard);
  return new Program<TreasuryStandard>(idl, provider);
}

export type { AgentRegistry, CapabilityRegistry, DisputeArbitration, FeeCollector, GovernanceProgram, NxsStaking, ProofVerifier, TaskMarket, TemplateRegistry, TreasuryStandard };
export { PublicKey };

export type SaepProgramFactory = (p: AnchorProvider, c: ClusterConfig) => Program<Idl>;
