// Generated by packages/sdk/scripts/gen.ts — do not edit by hand.

import { AnchorProvider, Program, Idl } from '@coral-xyz/anchor';
import { Connection, PublicKey, Transaction, VersionedTransaction } from '@solana/web3.js';

import agentRegistryIdl from '../idl/agent_registry.json' with { type: 'json' };
import capabilityRegistryIdl from '../idl/capability_registry.json' with { type: 'json' };
import disputeArbitrationIdl from '../idl/dispute_arbitration.json' with { type: 'json' };
import feeCollectorIdl from '../idl/fee_collector.json' with { type: 'json' };
import governanceProgramIdl from '../idl/governance_program.json' with { type: 'json' };
import proofVerifierIdl from '../idl/proof_verifier.json' with { type: 'json' };
import taskMarketIdl from '../idl/task_market.json' with { type: 'json' };
import treasuryStandardIdl from '../idl/treasury_standard.json' with { type: 'json' };
import type { AgentRegistry } from '../generated/agent_registry.js';
import type { CapabilityRegistry } from '../generated/capability_registry.js';
import type { DisputeArbitration } from '../generated/dispute_arbitration.js';
import type { FeeCollector } from '../generated/fee_collector.js';
import type { GovernanceProgram } from '../generated/governance_program.js';
import type { ProofVerifier } from '../generated/proof_verifier.js';
import type { TaskMarket } from '../generated/task_market.js';
import type { TreasuryStandard } from '../generated/treasury_standard.js';
import type { ClusterConfig, SaepProgramName } from '../cluster/index.js';

export interface BrowserWallet {
  publicKey: PublicKey;
  signTransaction<T extends Transaction | VersionedTransaction>(tx: T): Promise<T>;
  signAllTransactions<T extends Transaction | VersionedTransaction>(txs: T[]): Promise<T[]>;
}

export interface ProviderInput {
  connection: Connection;
  wallet: BrowserWallet;
}

export function makeProvider({ connection, wallet }: ProviderInput): AnchorProvider {
  return new AnchorProvider(connection, wallet as unknown as AnchorProvider['wallet'], {
    commitment: 'confirmed',
  });
}

function withAddress<T extends Idl>(idl: unknown, id: PublicKey): T {
  return { ...(idl as T), address: id.toBase58() } as T;
}

export function agentRegistryProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<AgentRegistry> {
  const idl = withAddress<AgentRegistry>(agentRegistryIdl as unknown as AgentRegistry, config.programIds.agentRegistry);
  return new Program<AgentRegistry>(idl, provider);
}

export function capabilityRegistryProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<CapabilityRegistry> {
  const idl = withAddress<CapabilityRegistry>(capabilityRegistryIdl as unknown as CapabilityRegistry, config.programIds.capabilityRegistry);
  return new Program<CapabilityRegistry>(idl, provider);
}

export function disputeArbitrationProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<DisputeArbitration> {
  const idl = withAddress<DisputeArbitration>(disputeArbitrationIdl as unknown as DisputeArbitration, config.programIds.disputeArbitration);
  return new Program<DisputeArbitration>(idl, provider);
}

export function feeCollectorProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<FeeCollector> {
  const idl = withAddress<FeeCollector>(feeCollectorIdl as unknown as FeeCollector, config.programIds.feeCollector);
  return new Program<FeeCollector>(idl, provider);
}

export function governanceProgramProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<GovernanceProgram> {
  const idl = withAddress<GovernanceProgram>(governanceProgramIdl as unknown as GovernanceProgram, config.programIds.governanceProgram);
  return new Program<GovernanceProgram>(idl, provider);
}

export function proofVerifierProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<ProofVerifier> {
  const idl = withAddress<ProofVerifier>(proofVerifierIdl as unknown as ProofVerifier, config.programIds.proofVerifier);
  return new Program<ProofVerifier>(idl, provider);
}

export function taskMarketProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<TaskMarket> {
  const idl = withAddress<TaskMarket>(taskMarketIdl as unknown as TaskMarket, config.programIds.taskMarket);
  return new Program<TaskMarket>(idl, provider);
}

export function treasuryStandardProgram(
  provider: AnchorProvider,
  config: ClusterConfig,
): Program<TreasuryStandard> {
  const idl = withAddress<TreasuryStandard>(treasuryStandardIdl as unknown as TreasuryStandard, config.programIds.treasuryStandard);
  return new Program<TreasuryStandard>(idl, provider);
}

export type { AgentRegistry, CapabilityRegistry, DisputeArbitration, FeeCollector, GovernanceProgram, ProofVerifier, TaskMarket, TreasuryStandard };
export { PublicKey };

export type SaepProgramFactory = (p: AnchorProvider, c: ClusterConfig) => Program<Idl>;
